### ISSUE TITLE
Clear input field programatically

### ISSUE THREAD

**Issue by shiro** [OmarCastro/rofi-blocks#10]
I wanted to ask whether it's possible to clear the input field.

I expected the following message to clear the field since i'm sending an empty string:
```
{
    "input": "",
}
```

However empty strings seem to be ignored, same with `null`.

Sending a single whitespace is a temporary hack since rofi will ignore it by default, however there's still a whitespace in the input field and it's not pretty.

I did not test clearing other fields like `prompt`, but my guess is that the issue also applies there.

Thanks for your help!

**Comment by OmarCastro** [comment]
Hello, I was thinking of implementing this when developing another project.

It is not implemented for now, but I will focus on it now

**Comment by shiro** [comment]
No stress, I appreciate the reply and work on open source projects that are this versatile and easy to use, thanks! :heart:

**Comment by OmarCastro** [comment]
No problem! :) , was about to work in this project anyway.

It seems that the feature was implemented, but there was missing a part of documentation, and there was a bug that caused that problem. Fixed it and added an example to show it working.

EDIT: the example is the `examples/prompt_input_test.sh`

**Comment by OmarCastro** [comment]
Since it is solved and there is no response, I will close this issue
