### ISSUE TITLE
How to hide message element

### ISSUE THREAD

**Issue by owzim** [OmarCastro/rofi-blocks#12]
First of all: great software. I like rofi a lot but with the option of realtime updating the results with rofi-blocks, it is perfect.

Problem: 

neither 

```json
{ "message": false }
```

nor

```json
{ "message": "" }
```

seems to work.

I also tried to mess with rofi themes to hide it, but without luck.

**Comment by owzim** [comment]
Did not understand rofi's layout system in full, but now this works (`*.rasi` file):

```css
window {
  children: [ inputbar, listview ];
}
```

which explicitly does not include `message` as a child.

**Comment by OmarCastro** [comment]
Hello @owzim, actually I was not aware that it was possible to hide a message, and since it is possible to do it I will reopen this issue.
