### ISSUE TITLE
Feature Request: Add Icon support

### ISSUE THREAD

**Issue by owzim** [OmarCastro/rofi-blocks#13]
Rofi has had icon support for some time now:

https://github.com/davatorium/rofi/wiki/mode-Specs

```sh
echo -en "aap\0icon\x1ffolder\n"
```

I suggest including the icon property in the line object

```json
[
  {"icon":"firefox", "text":"or both", "urgent":true, "highlight":true, "markup":true},
  {"icon":"/abs/path/to/icon.svg", "text":"Foo bar baz"}
]
```

**Comment by OmarCastro** [comment]
Hello @owzim, yes it is in my plans to add icons in the near future, however, I do not know what is the the best strategy to handle the value of the icon.

For now you can do it with icon fonts; or even color fonts as shown on `show_lines.sh` example

**Comment by owzim** [comment]
@OmarCastro thanks fo the reply.

What do you mean with 'best strategy to handle the value'? Isn't it just a matter of just passing that special string to rofi? I mean, the actual icon handling/rendering is taken care of already:

```sh
echo -en "Firefox\0icon\x1ffirefox\nChromium\0icon\x1fchromium\n" | rofi -dmenu -show-icons
```

**Comment by OmarCastro** [comment]
Icon is now is supported the same way rofi handles it, it reuses rofi's icon query helper

Closing it now
