### ISSUE TITLE
created aur package

### ISSUE THREAD

**Issue by fogine** [OmarCastro/rofi-blocks#2]
Added a package to the [AUR](https://aur.archlinux.org/packages/rofi-blocks-git/)

You are welcome to take ownership @OmarCastro

**Comment by hingew** [comment]
Thanks @fogine!

**Comment by OmarCastro** [comment]
Hey @fogine thanks! Now that I'm back to OSS development, and Arch as well, I would be happy to maintain the package.

**Comment by fogine** [comment]
What is your username on `AUR` @OmarCastro ?
I can't find settings for ownership but I can certainly add you as co-maintainer..

**Comment by OmarCastro** [comment]
My username is the same: OmarCastro

**Comment by fogine** [comment]
Done. Added as the co-maintainer of https://aur.archlinux.org/packages/rofi-blocks-git/
