### ISSUE TITLE
"input change" event timeout

### ISSUE THREAD

**Issue by vredesbyyrd** [OmarCastro/rofi-blocks#22]
Hi, 

It would be nice to have a optional timeout for the `send` input action. As it is now each key-press triggers an input change which is a good default, but if the user is processing something heavy eg. web scraping or a large database, it would be awesome to have the option to _wait until the user stops typing_ to begin the processing by adding a small timeout/debounce routine. 

If input action is set to `send` timeout defaults to 0, otherwise user defines in milliseconds. If input action is set to filter timeout is not an option.  

`{"input action": "send, 500"}` 

or 

`{"input action timeout": 500}`

I have tried to implement a timeout from the script side of things (in lua) but have not had success. Which is probably more of a reflection on me :/ Anyway this is just a feature request / suggestion that I personally would find useful and from looking at some other peoples scripts I get that impression as well. On the flip side I can see the argument that this is overkill for rofi and not worth the added complexity.

**Comment by fogine** [comment]
You correctly assume this can be done already from within the script that
should be enough..
For example implementation you can look at [rofi-search](
https://github.com/fogine/rofi-search) which is written in Javascript on
top of `rofi-blocks`..
After you stop typing search query it will trigger a search..

 The functionality you want is highly implementation dependent.

**Comment by vredesbyyrd** [comment]
@fogine 

> 
> You correctly assume this can be done already from within the script that
> should be enough..

Thanks for confirming that, and agreed, it should be enough.

I'll take a look at your Javascript implementation and see if I can learn anything applicable to accomplishing similar in lua, I have not been able to figure it out yet but it has to be doable.
