### ISSUE TITLE
Would you consider creating a version tag/release?

### ISSUE THREAD

**Issue by Animeshz** [OmarCastro/rofi-blocks#25]
I'm trying to have this package up in the [void-linux/void-packages](https://github.com/void-linux/void-packages), the quality check requirements include to have a build from a static tarball archive and not from tip of the development branch. Would you create a tag?

**Comment by jirutka** [comment]
I’m packaging rofi-blocks for Alpine Linux and having release tags would be really better.

**Comment by OmarCastro** [comment]
Hello, back from other projects, I did a project cleanup and made a release. I am going to develop it further, as well as create tests, github pages & badges, just  as I did with [cmd-polkit](https://github.com/OmarCastro/cmd-polkit)

**Comment by Animeshz** [comment]
Thanks :^)
