### ISSUE TITLE
Fails to render data if multibyte unicode characters are present

### ISSUE THREAD

**Issue by fogine** [OmarCastro/rofi-blocks#3]
If I send to stdout:  

```json
{
    "prompt": "search",
    "input action": "send",
    "lines": [
        {
            "text": "– aka. \u2013",
            "markup": true
        }
    ]
}
```

rofi does not render anything as long as the `lines` text data include unicode character `\u2013` or its decoded variant `–`.
blocks does not print any warning or errors either.

It doesn't seem that `rofi` has an issue with rendering multibyte characters:
> echo -e '–\u2013' | rofi -dmenu

works fine

**Comment by fogine** [comment]
@DaveDavenport , I'm reading the source code of `rofi` and `rofi-blocks` and trying to fix this issue. However, I'm not `c` programmer so I'm quite lost.
Could you, please, direct me to a way of solving this?  

First, I thought, there is a problem with using `gchar` instead of `gunichar`... However interface method `_get_display_value` is expecting generic `char`.

Basically, `rofi-blocks` receives json-data from my script and parses `lines` text field   (line 311) and adds it to `pageData` object that holds all data being rendered by `rofi`:
https://github.com/OmarCastro/rofi-blocks/blob/a865916da678413e6b2476bcd01f37f0a23a9164/src/blocks.c#L306-L315

`pageData` are then synchronized with `rofi` in `_get_display_value`:
https://github.com/OmarCastro/rofi-blocks/blob/a865916da678413e6b2476bcd01f37f0a23a9164/src/blocks.c#L690-L696

However somewhere in between, encoding is messed up so if `rofi-blocks` receives any data that contain multibyte characters, `rofi` does not render anything at all...

**Comment by DaveDavenport** [comment]
Rofi assumes utf-8 data. So validate that the input is utf-8, not sure how that works with json.

**Comment by fogine** [comment]
Now I understand whats going on. The bug is here:

https://github.com/OmarCastro/rofi-blocks/blob/a865916da678413e6b2476bcd01f37f0a23a9164/src/blocks.c#L462-L478

As `g_io_channel_read_chars` reads only 1B at time... When it reaches first multi-byte character, the `g_io_channel_read_chars` sets `&bytes_read=0` which results in aborting of input data reading.  

We need to use `g_io_channel_read_unichar` to support multi-byte strings.  
The problem is that `g_io_channel_read_unichar` does not set `bytes_read` as `g_io_channel_read_chars` does and current design relies on the `bytes_read` data to be able to temporarily stop reading from wrapper output stream without ever closing it. Which is a bit unfortunate as it should wait for the stream to be closed...
