### ISSUE TITLE
change `active entry` to newly added line

### ISSUE THREAD

**Issue by ghost** [OmarCastro/rofi-blocks#31]
hi thanks for your amazing work.
this does not work:
```bash
echo '{ "lines": [ "one","two","three" ], "active entry": 2}'
```
but this does
```bash
echo '{ "lines": [ "one","two","three" ]}'
sleep 0.3
echo '{ "lines": [ "one","two","three" ], "active entry": 2}'
```
i'm guessing it can't change active entry to a line that's being added.

**Comment by OmarCastro** [comment]
Hello, I create a test validating this issue here: https://omarcastro.github.io/rofi-blocks/test-report#ui-test--active-entry-should-work-on-first-paint

Now I am going to fix this...

**Comment by OmarCastro** [comment]
Fix applied, going to close this issue, if it did not fix the problem, feel free to reopen this issue
