### ISSUE TITLE
Allow parameters of the wrapped script

### ISSUE THREAD

**Issue by johnbeard** [OmarCastro/rofi-blocks#7]
I'm working on a script that's got a few "modes". For example, say a it might be able to search "en.wikipedia" and "de.wikipedia". It would be nice to have a way to set the script up with some kind of parameters.

For now, I have a workaround where I can set the `-filter` in Rofi and consume that as a config command. The actual rofi filter can be re-set by a return message. However it's a bit clunky and fragile to do it that way.

If there was a `-blocks-args` parameter, that would mean the script can set itself up before it even starts receiving messages, eg:

    rofi -show blocks -modi blocks -blocks-wrap a_script.sh -blocks-args "-script -options"

**Comment by fogine** [comment]
Yes, that might be helpful. For the time being you can use environment variables for that purpose or wrap your script in another script where you set the arguments..

**Comment by johnbeard** [comment]
Indeed, a wrapper script is the easiest way for now. But with this parameter, you could describe it all from Myrmidon/rofi-bangs/i3 config, etc.

**Comment by OmarCastro** [comment]
I was thinking of making `-blocks-wrap` a command line so you can use something like this:

```
rofi -show blocks -modi blocks -blocks-wrap "script.sh -arg1 -arg2 arg3"
```

With the commit I made earlier it should be possible to do this way

**Comment by johnbeard** [comment]
Thanks! Confirmed that it's working for me.

**Comment by OmarCastro** [comment]
You are welcome. Very well, I shall close this issue then.
